### ISSUE TITLE
Fail to compile on macOS

### ISSUE THREAD

**Issue by Co1lin** [decaf-lang/minidecaf-tutorial#6]
Hi,
I tried to compile the C program in the doc on macOS, but failed:

```shell
❯ cat test.c
#include <stdio.h>
int main() { printf("Hello world!\n"); }
❯ riscv64-unknown-elf-gcc -O3 test.c -march=rv32im -mabi=ilp32
riscv64-unknown-elf-gcc: fatal error: Can't found suitable multilib set for '-march=rv32im'/'-mabi=ilp32'
compilation terminated.
```

However, I can generate the assembly code:
```shell
❯ riscv64-unknown-elf-gcc -O3 -S test.c -march=rv32im -mabi=ilp32
❯ cat test.s
	.file	"test.c"
	.option nopic
	.attribute arch, "rv32i2p0_m2p0"
	.attribute unaligned_access, 0
	.attribute stack_align, 16
	.text
	.section	.rodata.str1.4,"aMS",@progbits,1
	.align	2
.LC0:
	.string	"Hello world!"
	.section	.text.startup,"ax",@progbits
	.align	2
	.globl	main
	.type	main, @function
main:
	lui	a0,%hi(.LC0)
	addi	sp,sp,-16
	addi	a0,a0,%lo(.LC0)
	sw	ra,12(sp)
	call	puts
	lw	ra,12(sp)
	li	a0,0
	addi	sp,sp,16
	jr	ra
	.size	main, .-main
	.ident	"GCC: (SiFive GCC-Metal 10.2.0-2020.12.8) 10.2.0"
```

Additionally, when I removed the options for 32-bit, It worked well. But it didn't meet the requirement of this course.

```shell
❯ riscv64-unknown-elf-gcc -O3 test.c
❯ ls | grep a.out
a.out
```

BTW, the last snippet on [this page](https://decaf-lang.github.io/minidecaf-tutorial/docs/step0/riscv_env.html) which uses `qemu-riscv32` is not compatible for macOS. It can be removed to avoid confusion.

**Comment by Co1lin** [comment]
Problem solved by using the download link to `riscv64-unknown-elf-gcc-8.3.0-2020.04.0-x86_64-apple-darwin.tar.gz`. But I am wondering why toolchains downloaded from `https://www.sifive.com/software -> Prebuilt RISC‑V
GCC Toolchain and Emulator -> GNU Embedded Toolchain — v2020.12.8 -> macOS` cannot work...

**Comment by namasikanam** [comment]
This is caused by [issue #13](https://github.com/sifive/freedom-tools/issues/81) of SiFive prebuilt risc-v gcc toolchain. Thus, unfortunately, we can only use [August 2020 release](https://github.com/sifive/freedom-tools/releases/tag/v2020.08.0) or prior for now.

**Comment by Co1lin** [comment]
Thanks~
