### ISSUE TITLE
Where can I get the frame code?

### ISSUE THREAD

**Issue by ICppl** [decaf-lang/minidecaf-tutorial#8]

**Comment by namasikanam** [comment]
Sorry, we currently do not provide the start code publicly. There're some problems about licence to handle with. I'll make the code public after solving the problems, maybe a few days later. Thanks for your patience!

**Comment by snowzhaozhj** [comment]
Ok. Thank you for providing such a good tutorial! I'm looking forward to see the code！

**Comment by ICppl** [comment]
Ok! Thank you for providing such a good tutorial! I'm looking forward to see the code!

**Comment by namasikanam** [comment]
After discussion, we finally decide that the start code is not open to the public this year. The start code will be published perhaps the next year or later, after we make sure the lab is good enough.

Apologize for this closed source decision. I personally suggest you build a compiler from scratch. The [frameworks of 2020 Autumn](https://github.com/decaf-lang/minidecaf) should be useful references.
