### ISSUE TITLE
关于assignment的文法

### ISSUE THREAD

**Issue by snowzhaozhj** [decaf-lang/minidecaf-tutorial#9]
对于assignment的文法：
```
assignment
    : conditional
    | unary '=' expression
```
我觉得改成下面这样更好：
```
assignment
    : conditional
    | postfix '=' expression
```
unary解析成`('-'|'~'|'!') unary`的时候应该不是合法的C表达式。

**Comment by namasikanam** [comment]
呃我觉得 `('-'|'~'|'!') unary` 应该是合法的 C 表达式吧，比如 `int main() { return !!1; }` 是合法的 C 程序。你可以通过使用 gcc 编译来确认其合法性，或者参见 [C17 标准](https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf) 6.5.3。

**Comment by snowzhaozhj** [comment]
但是后面还有一个赋值运算符，解析成`('-'|'~'|'!') unary`的时候应该不属于左值了吧

**Comment by namasikanam** [comment]
奥奥……我明白你想说什么了。从目前 11 个 step 的这个语言来看，改成你给出的文法确实可以将一些报错提前，让其从语义错误变成语法错误，从这个角度来讲确实更好。但这同时也会降低它的可扩展性，比如我想增加一个指针类型的话，还是依现有的文法为好。并且从与 C 语言兼容的角度考量，现有的文法也是更符合 C 语言的设计的。

感谢反馈！你说得很有道理，不过语言设计往往面临诸多考量的权衡，我目前还是觉得现有的文法较好。
